version: '3.8'

services:
  example-frontend:
    image: example-front 
    ports:
      - 5000:5000
    container_name: frontend-example


  example-backend:
    image: example-back 
    ports: 
      - 8080:8080
    container_name: backend-example

